//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public Cities()
        {
            this.TeacherExperiences = new HashSet<TeacherExperiences>();
        }
    
        public int CityId { get; set; }
        public int StateId { get; set; }
        public string Name { get; set; }
    
        public virtual States States { get; set; }
        public virtual ICollection<TeacherExperiences> TeacherExperiences { get; set; }
    }
}
