//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeDiscountTypes
    {
        public FeeDiscountTypes()
        {
            this.FeeCollectionsDetails = new HashSet<FeeCollectionsDetails>();
            this.FeeStructures = new HashSet<FeeStructures>();
            this.FeeTypes = new HashSet<FeeTypes>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
    
        public virtual ICollection<FeeCollectionsDetails> FeeCollectionsDetails { get; set; }
        public virtual ICollection<FeeStructures> FeeStructures { get; set; }
        public virtual ICollection<FeeTypes> FeeTypes { get; set; }
    }
}
