//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeDueOnFrequencies
    {
        public FeeDueOnFrequencies()
        {
            this.FeeTypes = new HashSet<FeeTypes>();
            this.FeeDueOnInterval = new HashSet<FeeDueOnInterval>();
        }
    
        public int ID { get; set; }
        public int FeeCycleID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
    
        public virtual FeeCycles FeeCycles { get; set; }
        public virtual ICollection<FeeTypes> FeeTypes { get; set; }
        public virtual ICollection<FeeDueOnInterval> FeeDueOnInterval { get; set; }
    }
}
