//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeePaymentsDetails
    {
        public int FeePaymentDetailID { get; set; }
        public int FeePaymentID { get; set; }
        public int FeeCollectionAgingID { get; set; }
        public decimal PaidAmount { get; set; }
    
        public virtual FeeCollectionsAging FeeCollectionsAging { get; set; }
        public virtual FeePayments FeePayments { get; set; }
    }
}
