//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeStructures
    {
        public int FeeStructureID { get; set; }
        public int ClassID { get; set; }
        public int FeeTypeID { get; set; }
        public decimal Fee { get; set; }
        public Nullable<int> FeeDiscountTypeID { get; set; }
        public decimal DiscountRate { get; set; }
        public string DiscountOption { get; set; }
        public decimal DiscountValue { get; set; }
        public decimal NetFee { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual FeeDiscountTypes FeeDiscountTypes { get; set; }
        public virtual FeeTypes FeeTypes { get; set; }
    }
}
