//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualificationTypes
    {
        public QualificationTypes()
        {
            this.TeacherQualifications = new HashSet<TeacherQualifications>();
        }
    
        public int QualificationTypeId { get; set; }
        public string QualificationType { get; set; }
    
        public virtual ICollection<TeacherQualifications> TeacherQualifications { get; set; }
    }
}
