//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsClasses
    {
        public int StudentClassId { get; set; }
        public int StudentId { get; set; }
        public int ShiftId { get; set; }
        public int ClassId { get; set; }
        public int SectionId { get; set; }
        public int BatchID { get; set; }
        public string RollNo { get; set; }
    
        public virtual Batches Batches { get; set; }
        public virtual Classes Classes { get; set; }
        public virtual Sections Sections { get; set; }
        public virtual Shifts Shifts { get; set; }
        public virtual Students Students { get; set; }
    }
}
