//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsEmergencyContactDetails
    {
        public int StudentEmergencyContactDetailId { get; set; }
        public int StudentId { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonRelation { get; set; }
        public string Email { get; set; }
        public string WorkPhoneNo { get; set; }
        public string HomePhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string OtherDetails { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
