//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int TeacherId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string IDNo { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Nationalities Nationalities { get; set; }
    }
}
