//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherQualifications
    {
        public int TeacherQualificationId { get; set; }
        public int TeacherId { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> QualificationTypeId { get; set; }
        public string ScoreType { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string Duration { get; set; }
        public string Majors { get; set; }
        public string InstitutionName { get; set; }
    
        public virtual QualificationTypes QualificationTypes { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
